<?php

return array(
    'types' => array(
        'Veldspar',
        'Concentrated Veldspar',
        'Dense Veldspar',
        'Scordite',
        'Condensed Scordite',
        'Massive Scordite',
        'Pyroxeres',
        'Solid Pyroxeres',
        'Viscous Pyroxeres',
        'Plagioclase',
        'Azure Plagioclase',
        'Rich Plagioclase',
        'Omber',
        'Silvery Omber',
        'Golden Omber',
        'Kernite',
        'Luminous Kernite',
        'Fiery Kernite',
        'Jaspet',
        'Pure Jaspet',
        'Pristine Jaspet',
        'Hemorphite',
        'Vivid Hemorphite',
        'Radiant Hemorphite',
        'Hedbergite',
        'Vitric Hedbergite',
        'Glazed Hedbergite',
        'Gneiss',
        'Iridescent Gneiss',
        'Prismatic Gneiss',
        'Dark Ochre',
        'Onyx Ochre',
        'Obsidian Ochre',
        'Crokite',
        'Sharp Crokite',
        'Crystalline Crokite',
        'Spodumain',
        'Bright Spodumain',
        'Gleaming Spodumain',
        'Bistot',
        'Triclinic Bistot',
        'Monoclinic Bistot',
        'Arkonor',
        'Crimson Arkonor',
        'Prime Arkonor',
        'Mercoxit',
        'Magma Mercoxit',
        'Vitreous Mercoxit',
        'Blue Ice',
        'Thick Blue Ice',
        'Azure Ice',

        // Gallente Fuel Block Materials
        'Heavy Water',
        'Liquid Ozone',
        'Oxygen Isotopes',
        'Coolant',
        'Enriched Uranium',
        'Mechanical Parts',
        'Robotics',
        'Oxygen',
    ),

    'stations' => array(
        'Haine VI - Moon 6 - Federal Intelligence Office Assembly Plant',
        'Droselory VI - Moon 17 - CreoDron Warehouse',
        'Allebin VIII - Moon 4 - CreoDron Factory',
    ),
);