<?php

return array(
    // Item groups.  Items specified by name
    'groups' => [
        'ore' => [
            'Veldspar',
            'Concentrated Veldspar',
            'Dense Veldspar',
            'Scordite',
            'Condensed Scordite',
            'Massive Scordite',
            'Pyroxeres',
            'Solid Pyroxeres',
            'Viscous Pyroxeres',
            'Plagioclase',
            'Azure Plagioclase',
            'Rich Plagioclase',
            'Omber',
            'Silvery Omber',
            'Golden Omber',
            'Kernite',
            'Luminous Kernite',
            'Fiery Kernite',
            'Jaspet',
            'Pure Jaspet',
            'Pristine Jaspet',
            'Hemorphite',
            'Vivid Hemorphite',
            'Radiant Hemorphite',
            'Hedbergite',
            'Vitric Hedbergite',
            'Glazed Hedbergite',
            'Gneiss',
            'Iridescent Gneiss',
            'Prismatic Gneiss',
            'Dark Ochre',
            'Onyx Ochre',
            'Obsidian Ochre',
            'Crokite',
            'Sharp Crokite',
            'Crystalline Crokite',
            'Spodumain',
            'Bright Spodumain',
            'Gleaming Spodumain',
            'Bistot',
            'Triclinic Bistot',
            'Monoclinic Bistot',
            'Arkonor',
            'Crimson Arkonor',
            'Prime Arkonor',
            'Mercoxit',
            'Magma Mercoxit',
            'Vitreous Mercoxit',
            'Compressed Veldspar',
            'Compressed Concentrated Veldspar',
            'Compressed Dense Veldspar',
            'Compressed Scordite',
            'Compressed Condensed Scordite',
            'Compressed Massive Scordite',
            'Compressed Pyroxeres',
            'Compressed Solid Pyroxeres',
            'Compressed Viscous Pyroxeres',
            'Compressed Plagioclase',
            'Compressed Azure Plagioclase',
            'Compressed Rich Plagioclase',
            'Compressed Omber',
            'Compressed Silvery Omber',
            'Compressed Golden Omber',
            'Compressed Kernite',
            'Compressed Luminous Kernite',
            'Compressed Fiery Kernite',
            'Compressed Jaspet',
            'Compressed Pure Jaspet',
            'Compressed Pristine Jaspet',
            'Compressed Hemorphite',
            'Compressed Vivid Hemorphite',
            'Compressed Radiant Hemorphite',
            'Compressed Hedbergite',
            'Compressed Vitric Hedbergite',
            'Compressed Glazed Hedbergite',
            'Compressed Gneiss',
            'Compressed Iridescent Gneiss',
            'Compressed Prismatic Gneiss',
            'Compressed Dark Ochre',
            'Compressed Onyx Ochre',
            'Compressed Obsidian Ochre',
            'Compressed Crokite',
            'Compressed Sharp Crokite',
            'Compressed Crystalline Crokite',
            'Compressed Spodumain',
            'Compressed Bright Spodumain',
            'Compressed Gleaming Spodumain',
            'Compressed Bistot',
            'Compressed Triclinic Bistot',
            'Compressed Monoclinic Bistot',
            'Compressed Arkonor',
            'Compressed Crimson Arkonor',
            'Compressed Prime Arkonor',
            'Compressed Mercoxit',
            'Compressed Magma Mercoxit',
            'Compressed Vitreous Mercoxit',
        ],
        'ice' => [
            'White Glaze',
            'Pristine White Glaze',
            'Glacial Mass',
            'Smooth Glacial Mass',
            'Blue Ice',
            'Thick Blue Ice',
            'Clear Icicle',
            'Enriched Clear Icicle',
            'Glare Crust',
            'Dark Glitter',
            'Gelidus',
            'Krystallos',
            'Compressed White Glaze',
            'Compressed Pristine White Glaze',
            'Compressed Glacial Mass',
            'Compressed Smooth Glacial Mass',
            'Compressed Blue Ice',
            'Compressed Thick Blue Ice',
            'Compressed Clear Icicle',
            'Compressed Enriched Clear Icicle',
            'Compressed Glare Crust',
            'Compressed Dark Glitter',
            'Compressed Gelidus',
            'Compressed Krystallos',
        ],
        'pi' => [
            'Heavy Water',
            'Liquid Ozone',
            'Oxygen Isotopes',
            'Coolant',
            'Enriched Uranium',
            'Mechanical Parts',
            'Robotics',
            'Oxygen',
        ]
    ],
);